name: Feature Request / Task
description: Describe a feature or task for contributors to work on.
title: "[Feature] <Short Description>"
labels:
  - enhancement
  - frontend
  - backend
assignees: []

body:
  - type: markdown
    attributes:
      value: |
        ## Overview
        Provide a brief description of the feature or task. Explain its purpose and how it fits into the project.
  
  - type: input
    id: design_reference
    attributes:
      label: "Design Reference"
      description: "Attach or link to relevant design files, Figma, or any visual references needed for this feature."

  - type: textarea
    id: requirements
    attributes:
      label: "Requirements"
      description: "List specific tasks contributors need to complete. Mention key functionalities and expected behaviors. Highlight dependencies (e.g., API, CMS, or third-party integrations)."

  - type: textarea
    id: technical_notes
    attributes:
      label: "Technical Notes"
      description: "Provide any technical guidelines, best practices, or constraints. Specify relevant frameworks, libraries, or tools if necessary."

  - type: textarea
    id: acceptance_criteria
    attributes:
      label: "Acceptance Criteria"
      description: "Define what needs to be done for the task to be considered complete. Include testing or review requirements if applicable."

  - type: textarea
    id: additional_notes
    attributes:
      label: "Additional Notes"
      description: "Add any extra details or considerations that may help the contributor."

  - type: markdown
    attributes:
      value: |
        ---
        > **Note:** Before starting, please discuss in the comments if anything needs clarification.

