name: "Improvement Request"
description: "Suggest improvements for the Push Ambassador website."
title: "[Improvement] <Short Description>"
labels: ["improvement"]
assignees: []

body:
  - type: input
    id: name
    attributes:
      label: "Your Name"
      description: "Who is submitting this request?"
      placeholder: "Enter your name here"
    validations:
      required: true

  - type: textarea
    id: current_behavior
    attributes:
      label: "Current Behavior"
      description: "Describe the current state of the feature."
      placeholder: "Explain how it works now..."
    validations:
      required: true

  - type: textarea
    id: suggested_improvement
    attributes:
      label: "Suggested Improvement"
      description: "What changes do you suggest?"
      placeholder: "Explain how this can be improved..."
    validations:
      required: true

  - type: textarea
    id: benefit
    attributes:
      label: "Benefit of Improvement"
      description: "Why is this improvement necessary?"
      placeholder: "Explain why this should be changed..."
    validations:
      required: true

  - type: textarea
    id: additional_info
    attributes:
      label: "Additional Information"
      description: "Any extra details or references?"
      placeholder: "Provide any relevant links or screenshots..."
